databases:
  - name: Budget-App
    databaseName: budget_app_ghi6
    user: budget_app_ghi6_user

services:
  - type: web
    name: budget-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget-App
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false